# Generated by Django 3.2.25 on 2024-10-21 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authxs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='usertype',
            field=models.IntegerField(choices=[(1, '普通会员'), (2, '大会员'), (3, '超级会员')], default=1),
        ),
        migrations.DeleteModel(
            name='Token',
        ),
    ]
