# Generated by Django 3.2.25 on 2024-10-19 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authxs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'permissions': (('edit_menu', 'Can Edit Menu'),)},
        ),
    ]
