# Generated by Django 3.2.25 on 2024-10-19 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authxs', '0003_alter_menu_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
            ],
            options={
                'permissions': [('publish_article', 'Can publish articles'), ('archive_article', 'Can archive articles')],
            },
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
    ]
