# Generated by Django 3.2.25 on 2024-10-19 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authxs', '0003_alter_user_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='roles_for_user', to='authxs.Role', verbose_name='roles'),
        ),
    ]
