# Generated by Django 3.2.25 on 2024-10-19 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authxs', '0004_alter_user_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='permission',
            field=models.ManyToManyField(blank=True, to='authxs.Permission', verbose_name='permission'),
        ),
    ]
