# Generated by Django 3.2.25 on 2024-10-20 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authxs', '0005_alter_role_permission'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('is_reviewed', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': '文章表',
                'verbose_name_plural': '文章表',
                'permissions': [('can_review_article', 'Can review article')],
            },
        ),
    ]
